version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "3000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0 --cert=adhoc --debug
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
